### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by nunojesus** [RALMAZ/Record-Player#14]
Hello I saw that you havent a logotype, so If you need a contribute for graphic design Im here to help.
Your project is amazing!

Congrats!

**Comment by RALMAZ** [comment]
@nunojesus Oh, I have no words)
I would be infinitely glad of your contribution to the project :)

**Comment by nunojesus** [comment]
Great!

So let´s begin, do you have any request for the logo? Shape? Colors?

It´s only for desktop, are you thinking to make a app to android and ios too?

Greetings!

**Comment by nunojesus** [comment]
Your player record radio? what more can it do ?

**Comment by nunojesus** [comment]
for the concept I will focus on the radio.
Does it also record radio broadcasts? right?

**Comment by RALMAZ** [comment]
Ye, streaming as this for example `http://air.radiorecord.ru:805/mmbt_320`

**Comment by nunojesus** [comment]
Hello,

Here is some of the work that I done until now,

The first 3 logos the inspiration was the Radio Microphone, and the elementents that are in red represents the Rec button.

The other 3 logos the inspiration was the radio, the first radio was a player button and also a rec button, 

The second one is just a radio with the rec button in red, and the last one is the same of the second one but I add the radio waves in is antena. (This is my favourite)

See if you like one of this and send me your review.

![recordplayer](https://user-images.githubusercontent.com/34600369/40133806-bba1889e-5938-11e8-8360-76cc333cbdca.png)

**Comment by RALMAZ** [comment]
My God, its beautiful :stuck_out_tongue:

**Comment by RALMAZ** [comment]
The third such pretty and modern, and it will be incredibly cool to look on mobile applications :star2:

What do you think?)

**Comment by nunojesus** [comment]
I can put the app button on the other logos if you want.

**Comment by nunojesus** [comment]
I will do for all, but I only can do that tomorrow. 
Greetings

**Comment by RALMAZ** [comment]
Goodnight)

**Comment by nunojesus** [comment]
Here is the icon set, see what you like most.

![recordplayer222](https://user-images.githubusercontent.com/34600369/40169021-ed54f054-59bc-11e8-9157-a4cfc0257a28.png)

**Comment by RALMAZ** [comment]
Yee, 3th is awesome)) :+1: 

For app need ~300x300px  

Can i too take this 3 logo https://github.com/RALMAZ/Record-Player/issues/14#issuecomment-389607153 for README?

**Comment by nunojesus** [comment]
Yes you can.

Is this one that you want?

![sem titulo](https://user-images.githubusercontent.com/34600369/40171729-0c9766b6-59c4-11e8-8fd4-5c1473dd2021.png)

**Comment by RALMAZ** [comment]
Thank you very much for your contribution)
